INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('1','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('2','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('3','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('4','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('5','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('6','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('7','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('8','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('9','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('A','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('B','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('C','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('D','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('E','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('F','USD','EUR',10,9.8,'2020-02-03');
INSERT INTO CONVERT_AMOUNT_TRANSACTION (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_AMOUNT,CONVERTED_AMOUNT,TRANSACTION_DATE) VALUES ('G','USD','EUR',10,9.8,'2020-02-03');

